# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Fastlane
        run: fastlane release